apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  annotations:
    github.com/project-slug: kmridha92/python-app
    backstage.io/techdocs-ref: kmridha92/python-app/README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests